apiVersion: v1
name: redash
version: 0.2.1
appVersion: 9.0.0-beta.b42121
description: This is a fork from the redash contrib helm chart https://github.com/getredash/contrib-helm-chart
keywords:
  - redash
  - analytics
  - vizualisation
home: https://redash.io/
sources:
  - https://github.com/getredash/redash
icon: https://redash.io/assets/images/elements/redash-logo.svg
engine: gotpl
dependencies:
  - name: base
    repository: oci://europe-docker.pkg.dev/bbc-registry/helm-charts
    version: 1.240405.1000-H2e0c5b37
