dependencies:
  - name: redis
    version: "^19.1.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: postgresql
    version: "^15.2.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
