dependencies:
  - name: redis
    version: "^18.9.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: postgresql
    version: "^13.4.1"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
