dependencies:
  - name: redis
    version: "^10.5.3"
    repository: "@stable"
    condition: redis.enabled
  - name: postgresql
    version: "^8.3.4"
    repository: "@stable"
    condition: postgresql.enabled
