apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redash.adhocWorker.fullname" . }}
  labels:
    {{- include "redash.labels" . | nindent 4 }}
    app.kubernetes.io/component: adhocworker
spec:
  replicas: {{ .Values.adhocWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "redash.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: adhocworker
  template:
    metadata:
      labels:
        {{- include "redash.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: adhocworker
        {{- if .Values.adhocWorker.podLabels }}
        {{- tpl (toYaml .Values.adhocWorker.podLabels) $ | nindent 8 }}
        {{- end }}
      {{- if .Values.adhocWorker.podAnnotations }}
      annotations:
      {{ toYaml .Values.adhocWorker.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "redash.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.adhocWorker.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "redash.name" . }}-adhocworker
          securityContext:
            {{- toYaml .Values.adhocWorker.securityContext | nindent 12 }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repo }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", ". /config/dynamicenv.sh && /app/bin/docker-entrypoint worker"]
          volumeMounts:
            - name: config
              mountPath: /config
            {{- with .Values.adhocWorker.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe: {{ toYaml .Values.adhocWorker.livenessProbe | nindent 12 }}
          env:
          {{- include "redash.env" . | nindent 12 }}
          {{- range $key, $value := .Values.adhocWorker.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
          {{ if (include "redash.envFrom" .) }}
          envFrom:
          {{- include "redash.envFrom" . | nindent 12 }}
          {{- end }}
          {{- if .Values.adhocWorker.resources }}
          resources: {{ toYaml .Values.adhocWorker.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "redash.fullname" . }}
        {{- with .Values.adhocWorker.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    {{- if .Values.adhocWorker.nodeSelector }}
      nodeSelector: {{ toYaml .Values.adhocWorker.nodeSelector | nindent 8 }}
    {{- end }}
    {{- with .Values.adhocWorker.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.adhocWorker.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
    {{- end }}
