apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-migrations"
  labels:
    {{- include "redash.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    # This is what defines this resource as a hook.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: {{ .Values.migrations.ttlSecondsAfterFinished }}
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels: {{ include "redash.selectorLabels" . | nindent 8 }}
      {{- with .Values.migrations.podAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "redash.serviceAccountName" . }}
      restartPolicy: Never
      securityContext: {{ toYaml .Values.migrations.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "redash.name" . }}-server
        securityContext: {{ toYaml .Values.migrations.securityContext | nindent 10 }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repo }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - create_db
        env:
        {{- include "redash.env" . | nindent 10 }}
        {{- range $key, $value := .Values.migrations.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
        {{- end }}
        {{- if (include "redash.envFrom" .) }}
        envFrom:
        {{- include "redash.envFrom" . | nindent 10 }}
        {{- end}}
        {{- with .Values.migrations.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.migrations.volumeMounts }}
        volumeMounts: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.migrations.volumes }}
      volumes: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
