{{- if not .Values.server.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redash.fullname" . }}
  labels:
    {{- include "redash.labels" . | nindent 4 }}
type: Opaque
data:
  ## Start primary Redash configuration
  secretKey: {{ required "A secure random value for redash.secretKey is required" .Values.redash.secretKey | b64enc | quote }}
  googleClientSecret: {{ default "" .Values.redash.googleClientSecret | b64enc | quote }}
  ldapBindDnPassword: {{ default "" .Values.redash.ldapBindDnPassword | b64enc | quote }}
  cookieSecret: {{ required "A secure random value for redash.cookieSecret is required" .Values.redash.cookieSecret | b64enc | quote }}
  mailPassword: {{ default "" .Values.redash.mailPassword | b64enc | quote }}
  ## End primary Redash configuration
{{- end -}}