{{- if not .Values.server.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redash.fullname" . }}
  labels:
    {{- include "redash.labels" . | nindent 4 }}
type: Opaque
data:
  cookieSecret: {{ required "A secure random value for server.cookieSecret is required" .Values.server.cookieSecret | b64enc | quote }}
  secretKey: {{ required "A secure random value for server.secretKey is required" .Values.server.secretKey | b64enc | quote }}
{{- end -}}
{{- if not .Values.postgresql.existingSecret -}}
  # This ensures a random value is provided for postgresqlPassword.
  # This is validation only - the value is not used here - see also: https://github.com/helm/charts/issues/5167
  {{ $null := required "A secure random value for postgresql.postgresqlPassword is required" .Values.postgresql.postgresqlPassword }}
{{- end -}}