{{- if not .Values.server.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redash.fullname" . }}
  labels:
    {{- include "redash.labels" . | nindent 4 }}
type: Opaque
data:
  ## Start primary Redash configuration
  secretKey: {{ required "A secure random value for server.secretKey is required" .Values.server.secretKey | b64enc | quote }}
  googleClientSecret: {{ default "" .Values.server.googleClientSecret | b64enc | quote }}
  ldapBindDnPassword: {{ default "" .Values.server.ldapBindDnPassword | b64enc | quote }}
  cookieSecret: {{ required "A secure random value for server.cookieSecret is required" .Values.server.cookieSecret | b64enc | quote }}
  mailPassword: {{ default "" .Values.server.mailPassword | b64enc | quote }}
  ## End primary Redash configuration
{{- end -}}