{{ range $workerName, $config := .Values.workers -}}
{{- $workerConfig := merge (deepCopy $.Values.worker) $config }}
{{- $context := deepCopy $ | merge (dict "workerName" $workerName)}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redash.worker.fullname" $context }}
  labels: {{ include "redash.labels" $context | nindent 4 }}
spec:
  replicas: {{ $workerConfig.replicaCount }}
  selector:
    matchLabels: {{ include "redash.selectorLabels" $context | nindent 6 }}
  template:
    metadata:
      labels: {{ include "redash.selectorLabels" $context | nindent 8 }}
      {{- if $workerConfig.podLabels }}
      {{ tpl (toYaml $workerConfig.podLabels) $ | nindent 8 }}
      {{- end }}
      {{- with $workerConfig.podAnnotations -}}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{ with $.Values.imagePullSecrets -}}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end -}}
      serviceAccountName: {{ include "redash.serviceAccountName" $context }}
      securityContext: {{ toYaml $workerConfig.podSecurityContext | nindent 8 }}
      containers:
        {{- with $workerConfig.extraContainers -}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: {{ include "redash.name" $context }}-{{ $workerName }}worker
          securityContext: {{ toYaml $workerConfig.securityContext | nindent 12 }}
          image: {{ $.Values.image.registry }}/{{ $.Values.image.repo }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          args: 
            - worker
          {{ with $workerConfig.volumeMounts -}}
          volumeMounts: {{ toYaml . | nindent 12 }}
          {{- end -}}
          livenessProbe: {{ toYaml $workerConfig.livenessProbe | nindent 12 }}
          env:
          {{- include "redash.env" $ | nindent 12 }}
          {{- range $key, $value := $workerConfig.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
          {{- with (include "redash.envFrom" $) }}
          envFrom: {{ . | nindent 12 }}
          {{- end }}
          {{- with $workerConfig.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
      {{- with $workerConfig.volumes }}
      volumes: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $workerConfig.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $workerConfig.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $workerConfig.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
