{{- if and .Values.postgresql.enabled .Values.postgresqlMigration.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-postgres-migration
  labels:
    {{- include "redash.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres-migration-rbac
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-30"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "patch", "update", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "patch", "update", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-postgres-migration
  labels:
    {{- include "redash.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres-migration-rbac
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-30"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-postgres-migration
subjects:
- kind: ServiceAccount
  name: {{ include "redash.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
