apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redash.fullname" . }}
  labels:
    {{- include "redash.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "redash.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "redash.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
        {{- if .Values.server.podLabels }}
        {{- tpl (toYaml .Values.server.podLabels) $ | nindent 8 }}
        {{- end }}
      {{- with .Values.server.podAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{ with .Values.imagePullSecrets -}}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{ end -}}
      serviceAccountName: {{ include "redash.serviceAccountName" . }}
      securityContext: {{ toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        {{- with .Values.server.extraContainers -}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: {{ include "redash.name" . }}-server
          securityContext: {{ toYaml .Values.server.securityContext | nindent 12 }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repo }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- $volumeMounts := concat .Values.volumeMounts .Values.server.volumeMounts }}
          {{- with $volumeMounts }}
          volumeMounts: {{ toYaml . | nindent 12 }}
          {{- end }}
          args:
            - server
          env:
          {{- $envCtx := mergeOverwrite (deepCopy .) (dict "Values" (dict "env" .Values.server.env)) -}}
          {{- include "redash.env" $envCtx | nindent 12 }}
          {{- with (include "redash.envFrom" .) }}
          envFrom: {{ . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.server.httpPort }}
          {{- $defaultProbe := dict "httpGet" (dict "path" "/ping" "port" .Values.server.httpPort) -}}
          {{- with .Values.server.livenessProbe }}
          livenessProbe: {{ deepCopy . | mergeOverwrite $defaultProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.server.readinessProbe }}
          readinessProbe: {{ deepCopy . | mergeOverwrite $defaultProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.server.resources }}
          resources: {{ toYaml .Values.server.resources | nindent 12 }}
          {{- end }}
      {{- $volumes := concat .Values.volumes .Values.server.volumes -}}
      {{- with $volumes }}
      volumes: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
